# Generated by Django 4.2.9 on 2024-01-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='food',
            name='user',
        ),
    ]
