# Generated by Django 4.2.9 on 2024-01-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_drink_customer_remove_food_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='customer',
        ),
        migrations.AddField(
            model_name='orderdrink',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.customer'),
        ),
        migrations.AddField(
            model_name='orderfood',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.customer'),
        ),
    ]
