# Generated by Django 4.2.9 on 2024-01-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderdrink_status_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfood',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
