# Generated by Django 4.2.9 on 2024-01-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderfood_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdrink',
            name='on_road',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderfood',
            name='on_road',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
