# Generated by Django 4.2.9 on 2024-01-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_food_customer_orderdrink_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
