# Generated by Django 4.2.9 on 2024-01-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_food_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
