# Generated by Django 4.2.9 on 2024-01-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderfood_on_road'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdrink',
            name='on_road',
            field=models.BooleanField(default=False),
        ),
    ]
